KanoComputing/sonic-pi

debian/install
kdesktop/make-music.desktop
kdesktop/sonic-pi.xml

KanoComputing/peldins#1511
By adding this XML to `/usr/share/mime/packages`, the MIME type
`application/x-kano-make-music` becomes associated with the `.spi` file
extension. This allows all files with the extension to be launched, by
clicking them, in Sonic Pi. It also allows setting of the icon to be a
custom Sonic Pi one by creating the icon file in the icon theme (as
`mimetypes/application-x-kano-make-music.png`).

Add application/x-kano-make-music MIME information

---

icon/make-music.app

KanoComputing/peldins#1511
Adds MIME type information to the .app file so that the autogenerated
.desktop file contains the MimeType field. To be used in conjunction
with
KanoComputing/kano-apps/commit/d2e3e28e44ec4f92a586fdc0718aca1a741e6d2f

Add MIME type information to .app file

---

app/gui/qt/mainwindow.cpp

KanoComputing/peldins#1419
Implement the Save, Load, Share and Make Kano keyboard buttons to
perform the correct action in Sonic Pi.
cc @skarbat

Add Kano keyboard shortcuts

---

app/gui/qt/share_dialog.cpp

KanoComputing/peldins#1613
KanoComputing/peldins#1729
To keep track of the total number of shares in profile, the total share
count should be incremented whenever sharing.

Share: Increment count in profile when sharing

---

app/gui/qt/mainwindow.cpp

KanoComputing/peldins#1419
In the Kano kit, `xbindkeys` absorbs all of the special keys which are
being listened for by Sonic Pi (for Save, Share, Load and Make) so
instead offer more sane keyboard shortcuts (although some preferences
are already taken so some are a bit strange) to be re-triggered by the
`xbindkeys` script.

Shortcuts: Implement (more) sane keyboard shortcuts

---

app/gui/qt/SonicPi.pro
app/gui/qt/audio_tools.cpp
app/gui/qt/audio_tools.h
app/gui/qt/export_dialog.cpp
debian/control

Supersedes KanoComputing/sonic-pi/pull/38
KanoComputing/peldins#1691
The sample used to be encoded as MP3 but there are licensing concerns
with this so switch to use an open format.
Ensure that all of the offending MP3 code is removed and all
dependencies on non-free MP3 library packages is removed.
@convolu Makes some progress towards:
KanoComputing/peldins#1858
@pazdera @skarbat @Ealdwulf Could you please review?

Sample: Switch sample to be Ogg Vorbis

---

app/gui/qt/export_dialog.cpp
app/gui/qt/export_dialog.h

Limiting QLineEdit is simple, QTextEdit you need to do it yourself. Hence the new slot.
Related to: https://github.com/KanoComputing/peldins/issues/2142
cc @tombettany @alex5imon

sharing: Adding character limits according to the API

---

app/gui/qt/mainwindow.cpp

KanoComputing/peldins#2172
Sonic Pi overrides any audio settings that we may have otherwise set in
the system and thus plays at its own volume. This can be troublesome if
the user has sensory issues which they expect the master audio to be
able to solve so remove the ability for Sonic Pi to change the setting
for now.
cc @radujipa

Volume: Remove setting RPi audio

---

app/gui/qt/mainwindow.cpp
debian/postinst

KanoComputing/peldins#2215
The default workspace had zooming applied. Remove this and reset any
installs affected by this.

Workspace: Decrease default size

---

app/gui/qt/dbus_actions.cpp
app/gui/qt/dbus_actions.h
app/gui/qt/mainwindow.cpp
app/gui/qt/mainwindow.h
debian/changelog
debian/control
debian/rules

@tombettany this PR replaces this one: https://github.com/KanoComputing/sonic-pi/pull/44
I need to finish the unfolding of the shared filename into the workspace.
right now only the string is put into it.
cc @Ealdwulf

Load share signal

---

debian/postinst

I think this should fix the complaints we get during the initial install, @tombettany @convolu .
```
Setting up make-music (2.9-0.20160201) ...
dpkg: error: --compare-versions takes three arguments: <version> <relation> <version>
```
I have also added a test: https://github.com/KanoComputing/QA/commit/92f0b1207bf24e6299e0f1e228d4fba2c98db89b

Fixing postinst when we are installing for the first time

---

debian/changelog

KanoComputing/peldins#2394
Sonic Pi's version was updated to v2.10.0 so bump the Debian package
version to match.

Debian: Bump version to 2.10-0

---

app/gui/qt/mainwindow.cpp
app/gui/qt/mainwindow.h

KanoComputing/peldins#2389
When opening a save from the CLI, it would both overwrite what was
already in "Song 1's" tab and would display the tab of whichever "Song"
was last opened. Improve this by opening the save in the last tab (which
isn't used by our challenges) and switching to that tab.

Saves: Open saves from the CLI in a new tab

---

app/gui/qt/mainwindow.cpp
app/server/sonicpi/lib/sonicpi/runtime.rb
app/server/sonicpi/lib/sonicpi/util.rb

KanoComputing/os-dashboard#2392
Add back the loading of challenges into the workspaces at startup.
Also fix up some other things to do with loading workspaces.

Challenges: Load challenges into workspaces

---

app/gui/qt/mainwindow.cpp
app/gui/qt/share_dialog.cpp
app/gui/qt/share_dialog.h
debian/control

Related to https://trello.com/c/zqYL354D/38-integrate-unified-sharing-flow-on-all-apps
@tombettany @skarbat 
A few notes:
- The ShareDialog is essentially only used to perform a `save()` and then pop-up kano-share-gui. It is not executed as a Qt dialog anymore.
- What needs to happen is a refactor of the entire inheritance tree of death of the IODialog -> ExportDialog -> SaveDialog / ShareDialog to use a SaveManager which would take care of the functionality that is currently inside UI components.
- Also, because the app no longer is responsible from grabbing the share title, the file names have been changed to a timestamp.
- Yes, the approach isn't brilliant. I don't like it either. Depending on the time constrains we may or may not get the do the above. That being said, I'm not in …

Repurposed ShareDialog into launcher for kano-share-gui

---

app/gui/qt/share_dialog.cpp

@tombettany 
The sharing flow does not recognise `sonic-pi` as the app title, `make-music` is the one it's looking for.

Renamed sonic-pi to make-music as the share apt-title

---

icon/make-music.app

The '%f' appended to the launch command in the `.app` file is not
interpreted correctly by the dashboard. It is utilised by pcmanfm to
launch Sonic Pi with a file but with the transition away from classic
mode towards the dashboard, fixing it in the dashboard is preferable.
The solution here is to simply remove the string.
@Ealdwulf to review.
cc @radujipa @jonasskjoldan

Icon: Remove %f in launch command

---

icon/locale/es_AR/make-music.app

Set the priority field for the `es_AR` `.app` icon and remove entries
duplicated in the English version.
Per https://docs.google.com/spreadsheets/d/1t6uLVB0FAv04rW9gHtP3wnNYWgq-DcwNS74zEyN5fHE/edit?ts=58a48f50#gid=0
cc @radujipa @skarbat

i18n: Set priority for es_AR `.app` file

---

app/gui/qt/mainwindow.cpp

Given our internal mechanism of switching between HDMI and Jack
audio and disabling such switching, Sonic Pi bypasses that creating
system wide issues. One dangerous aspect is that it switches to
audio Jack at startup, which is at odds with our PiHat.

Removed ability to change audio output

---

challenges/es_AR/workspace_one.spi

The missing comment symbol caused the challenge to throw an error when
run as the comment text was executed. Resolve this by ensuring that they
are commented out.

Challenges: Fix missing comment on challenge two

---

app/gui/qt/load_source_dialog.cpp
app/gui/qt/mainwindow.cpp
challenges/es_AR/workspace_five.spi
challenges/es_AR/workspace_four.spi
challenges/es_AR/workspace_one.spi
challenges/es_AR/workspace_six.spi
challenges/es_AR/workspace_three.spi
challenges/es_AR/workspace_two.spi
challenges/es_AR/workspace_zero.spi
debian/changelog

The issue here is an obscure bug in Sonic Pi due to which the UTF-8
encoded challenges were encoded to UTF-8 again, causing the chars
to not render properly. Due to the obscurity of this, the challenges
themselves were encoded to Latin1; double UTF-8 encoding becomes the
right one... Additionally, the Load mechanism was also updated to be
able to load files which were saved with UTF-8 chars (loading the
challenge files from here creates issues).
**NOTE:** This is for the es_AR 3.9.2 image.

Fixed es_AR challenges rendering of UTF-8 characters

---

app/gui/qt/load_source_dialog.cpp
debian/changelog

This is to specify that the changes made in the es_AR image need to be rebuilt, tested, and released from master as well.

Bumped changelog with applied changes from v3.9.2 es_AR backports

---

debian/changelog
debian/control

Updated the runtime package dependency to play well on Debian Jessie and Stretch.
The development package for building the software remains the same.
Attaching query below for the records.
```
root@KXBN001:/# cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
root@KXBN001:/# apt-cache search libqscintilla
libqscintilla2-12v5 - Qt4 port of the Scintilla source code editing widget
libqscintilla2-12v5-dbg - Qt4 port of the Scintilla source code editing widget (debug)
libqscintilla2-designer - Qt4 Designer plugin for QScintilla 2 …
```

Adapted dependency for Debian Stretch
